### ISSUE TITLE
Aren’t the rates of the occlusion and release different in your design?

### ISSUE THREAD

**Issue by issuefiler** [sidneygasoto/Peristaltic-pump-3D-print#1]
While reading [your paper](https://pubs.acs.org/doi/10.1021/acsomega.1c07093), one question has come to mind.

-----

![Koslov peristaltic pump states drawn by @sidneygasoto](https://github.com/sidneygasoto/Peristaltic-pump-3D-print/assets/57908781/70d77804-a9a8-46a3-8bca-4f8b2beca42d)

 In your Koslov peristaltic pump design, the occlusion (“engaging”) of the roll 2 and the release (“disengaging”) of the roll 3 start and end within the same timeframe, while moving along one sector. They share the same _progress_.

-----

![image](https://github.com/sidneygasoto/Peristaltic-pump-3D-print/assets/57908781/da46470d-5cf1-41dd-981d-dee099e2e7ef)
![image](https://github.com/sidneygasoto/Peristaltic-pump-3D-print/assets/57908781/755e2bfe-59e4-4684-9b36-bccdb8531a6b)

 What I wonder is that, due to the circular shape of the rolls, the rates of the occlusion and the release are different in terms of area. The amount that the roll 2 occludes further at a certain time starts small and gets larger at the end. The amount that the roll 3 releases further at a certain time starts large and gets smaller at the end. Because of this, the roll 3 always makes slightly more void than the roll 2 fills until the occlusion and the release are complete.

-----

![Koslov peristaltic pump’s pressure plot](https://github.com/sidneygasoto/Peristaltic-pump-3D-print/assets/57908781/e2aa339d-c169-45e9-bad4-be04778016fd)

 I suspect this might be where the slight pressure drops of your Koslov peristaltic pump originate from.

-----

# Question

![Patent US 2006 0245964 A1, figure #1](https://github.com/sidneygasoto/Peristaltic-pump-3D-print/assets/57908781/ec65d58f-189a-4ba5-9d29-4da90d1762da)
![The expected pressure plot when the occlusion happens earlier](https://github.com/sidneygasoto/Peristaltic-pump-3D-print/assets/57908781/9d8de59f-e655-4e28-82f9-76b90cb92c25)

 If we make the occlusion by the roll 2 start a little earlier than the occlusion by the roll 3, just like the original pulseless peristaltic pump on Koslov’s patent, would it reduce the pressure deviation even further?

**Comment by issuefiler** [comment]
## They’re not different, apparently.


 Or…… I probably made a false assumption to begin with, that “the rollers are moving towards or away from the tube _**linearly (at a constant length per unit time)**_.”


![The seemingly identical rates of the occlusion and release](https://github.com/sidneygasoto/Peristaltic-pump-3D-print/assets/57908781/11176cc1-725a-43d1-b978-5636d98b865e)

 But now that I’ve drawn some circles on it, I see the rollers _**not**_ moving _linearly_ relative to the tube, and the rates of the occlusion and the release in terms of area _look identical_.


 ……Closing this issue as it’s been answered.

**Comment by sidneygasoto** [comment]
Dear colleague,
The main reason for the appearance of pulses at the peristaltic pump outlet is related to the pressure difference that exists between the outlet and between rollers 2 and 3 since there is a constant pressure of 1 meter of the water column at the outlet and pressure lower than atmospheric pressure since the pump suctions the product, then the product returns from the outlet to the pump as soon as roller 3 unblocks the passage, balancing the forces.
But your question is pertinent. I confess that I have not studied or carried out tests changing the position of the obstruction and unblocking points in the way you mentioned. This could give us another condition and minimize the pulses, but I believe it is impossible to eliminate.
